version: '3.8'
services:  
  api:    
    build: ./backend    
    container_name: creation_backend    
    ports:      
      - '3001:3001'    
  client:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: creation_client