version: '3.8'
services:   
  client:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: creation_client
  server:    
    build: ./backend    
    ports:      
      - '3001:3001'   
    container_name: creation_backend    
