version: '3.8'
services:   
  client:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: creation_client
    volumes:
      # - ./frontend/src:/creation/src 
      # - ./frontend/public:/creation/public
      # - ./frontend/package.json:/creation/package.json
      - ./frontend:/creation
    environment:
      - NODE_ENV=development  
    # stdin_open: true 
    tty: true  
  server:    
    build: ./backend    
    ports:      
      - '3001:3001'   
    container_name: creation_backend  
